AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true

  TargetRubyVersion: 2.1

Lint/Debugger:
  Exclude:
    - test/examples/*.rb

Style/FileName:
  Exclude:
    - lib/pry-byebug.rb

Style/ModuleFunction:
  Enabled: false

Style/ExtraSpacing:
  AllowForAlignment: false

inherit_from: .rubocop_todo.yml
