AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true

  TargetRubyVersion: 2.2

Lint/Debugger:
  Exclude:
    - test/examples/*.rb

Naming/FileName:
  Exclude:
    - lib/pry-byebug.rb

Style/ModuleFunction:
  Enabled: false

Layout/ExtraSpacing:
  AllowForAlignment: false

inherit_from: .rubocop_todo.yml
