language: ruby

before_script:
  - git config --local user.email 'travis@travis.ci'
  - git config --local user.name 'Travis CI'

script:
  - bundle exec rake
  - bundle exec overcommit --run

rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head

addons:
  code_climate:
    repo_token: f06a22b27a507a3054eb69873c9e3bbc9ef97476d6ef22eec8cd24686494cb2b
