---

sudo: false

language: ruby

before_install:
  - rvm reinstall $TRAVIS_RUBY_VERSION --patch
      http://github.com/k0kubun/ruby/commit/6747055326e634899f0efb0ba7cf46.patch

install:
  - gem update --system --no-document || test true
  - gem install bundler --no-document || test true
  - bundle install --jobs 3 --retry 3

before_script:
  - git config --local user.email 'travis@travis.ci'
  - git config --local user.name 'Travis CI'

script:
  - bundle exec rake
  - bundle exec overcommit --sign
  - bundle exec overcommit --run

rvm:
  - 2.0.0
  - 2.1.7
  - 2.2.3
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head

addons:
  code_climate:
    repo_token: f06a22b27a507a3054eb69873c9e3bbc9ef97476d6ef22eec8cd24686494cb2b
